#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL_ALL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyBanQuanCafe")]
	public partial class QLBanCafeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBan(Ban instance);
    partial void UpdateBan(Ban instance);
    partial void DeleteBan(Ban instance);
    partial void InsertTaiKhoanNhomNV(TaiKhoanNhomNV instance);
    partial void UpdateTaiKhoanNhomNV(TaiKhoanNhomNV instance);
    partial void DeleteTaiKhoanNhomNV(TaiKhoanNhomNV instance);
    partial void InsertBangPhanCongCV(BangPhanCongCV instance);
    partial void UpdateBangPhanCongCV(BangPhanCongCV instance);
    partial void DeleteBangPhanCongCV(BangPhanCongCV instance);
    partial void InsertCaLamViec(CaLamViec instance);
    partial void UpdateCaLamViec(CaLamViec instance);
    partial void DeleteCaLamViec(CaLamViec instance);
    partial void InsertChiTietHD(ChiTietHD instance);
    partial void UpdateChiTietHD(ChiTietHD instance);
    partial void DeleteChiTietHD(ChiTietHD instance);
    partial void InsertDanhSachMonGoi(DanhSachMonGoi instance);
    partial void UpdateDanhSachMonGoi(DanhSachMonGoi instance);
    partial void DeleteDanhSachMonGoi(DanhSachMonGoi instance);
    partial void InsertGiamGia(GiamGia instance);
    partial void UpdateGiamGia(GiamGia instance);
    partial void DeleteGiamGia(GiamGia instance);
    partial void InsertHoaDon(HoaDon instance);
    partial void UpdateHoaDon(HoaDon instance);
    partial void DeleteHoaDon(HoaDon instance);
    partial void InsertKhoNguyenLieu(KhoNguyenLieu instance);
    partial void UpdateKhoNguyenLieu(KhoNguyenLieu instance);
    partial void DeleteKhoNguyenLieu(KhoNguyenLieu instance);
    partial void InsertKhuVuc(KhuVuc instance);
    partial void UpdateKhuVuc(KhuVuc instance);
    partial void DeleteKhuVuc(KhuVuc instance);
    partial void InsertManHinh(ManHinh instance);
    partial void UpdateManHinh(ManHinh instance);
    partial void DeleteManHinh(ManHinh instance);
    partial void InsertMenu(Menu instance);
    partial void UpdateMenu(Menu instance);
    partial void DeleteMenu(Menu instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertNhomNguyenLieu(NhomNguyenLieu instance);
    partial void UpdateNhomNguyenLieu(NhomNguyenLieu instance);
    partial void DeleteNhomNguyenLieu(NhomNguyenLieu instance);
    partial void InsertNhomNhanVien(NhomNhanVien instance);
    partial void UpdateNhomNhanVien(NhomNhanVien instance);
    partial void DeleteNhomNhanVien(NhomNhanVien instance);
    partial void InsertPhanQuyen(PhanQuyen instance);
    partial void UpdatePhanQuyen(PhanQuyen instance);
    partial void DeletePhanQuyen(PhanQuyen instance);
    partial void InsertQuanLyThuChi(QuanLyThuChi instance);
    partial void UpdateQuanLyThuChi(QuanLyThuChi instance);
    partial void DeleteQuanLyThuChi(QuanLyThuChi instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    #endregion
		
		public QLBanCafeDataContext() : 
				base(global::BLL_ALL.Properties.Settings.Default.QuanLyBanQuanCafeConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLBanCafeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLBanCafeDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLBanCafeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLBanCafeDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Ban> Bans
		{
			get
			{
				return this.GetTable<Ban>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoanNhomNV> TaiKhoanNhomNVs
		{
			get
			{
				return this.GetTable<TaiKhoanNhomNV>();
			}
		}
		
		public System.Data.Linq.Table<BangPhanCongCV> BangPhanCongCVs
		{
			get
			{
				return this.GetTable<BangPhanCongCV>();
			}
		}
		
		public System.Data.Linq.Table<CaLamViec> CaLamViecs
		{
			get
			{
				return this.GetTable<CaLamViec>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietHD> ChiTietHDs
		{
			get
			{
				return this.GetTable<ChiTietHD>();
			}
		}
		
		public System.Data.Linq.Table<DanhSachMonGoi> DanhSachMonGois
		{
			get
			{
				return this.GetTable<DanhSachMonGoi>();
			}
		}
		
		public System.Data.Linq.Table<GiamGia> GiamGias
		{
			get
			{
				return this.GetTable<GiamGia>();
			}
		}
		
		public System.Data.Linq.Table<HoaDon> HoaDons
		{
			get
			{
				return this.GetTable<HoaDon>();
			}
		}
		
		public System.Data.Linq.Table<KhoNguyenLieu> KhoNguyenLieus
		{
			get
			{
				return this.GetTable<KhoNguyenLieu>();
			}
		}
		
		public System.Data.Linq.Table<KhuVuc> KhuVucs
		{
			get
			{
				return this.GetTable<KhuVuc>();
			}
		}
		
		public System.Data.Linq.Table<ManHinh> ManHinhs
		{
			get
			{
				return this.GetTable<ManHinh>();
			}
		}
		
		public System.Data.Linq.Table<Menu> Menus
		{
			get
			{
				return this.GetTable<Menu>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<NhomNguyenLieu> NhomNguyenLieus
		{
			get
			{
				return this.GetTable<NhomNguyenLieu>();
			}
		}
		
		public System.Data.Linq.Table<NhomNhanVien> NhomNhanViens
		{
			get
			{
				return this.GetTable<NhomNhanVien>();
			}
		}
		
		public System.Data.Linq.Table<PhanQuyen> PhanQuyens
		{
			get
			{
				return this.GetTable<PhanQuyen>();
			}
		}
		
		public System.Data.Linq.Table<QuanLyThuChi> QuanLyThuChis
		{
			get
			{
				return this.GetTable<QuanLyThuChi>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ban")]
	public partial class Ban : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaBan;
		
		private string _TenBan;
		
		private System.Nullable<int> _TrangThai;
		
		private string _MaKhuVuc;
		
		private EntitySet<ChiTietHD> _ChiTietHDs;
		
		private EntitySet<DanhSachMonGoi> _DanhSachMonGois;
		
		private EntityRef<KhuVuc> _KhuVuc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBanChanging(int value);
    partial void OnMaBanChanged();
    partial void OnTenBanChanging(string value);
    partial void OnTenBanChanged();
    partial void OnTrangThaiChanging(System.Nullable<int> value);
    partial void OnTrangThaiChanged();
    partial void OnMaKhuVucChanging(string value);
    partial void OnMaKhuVucChanged();
    #endregion
		
		public Ban()
		{
			this._ChiTietHDs = new EntitySet<ChiTietHD>(new Action<ChiTietHD>(this.attach_ChiTietHDs), new Action<ChiTietHD>(this.detach_ChiTietHDs));
			this._DanhSachMonGois = new EntitySet<DanhSachMonGoi>(new Action<DanhSachMonGoi>(this.attach_DanhSachMonGois), new Action<DanhSachMonGoi>(this.detach_DanhSachMonGois));
			this._KhuVuc = default(EntityRef<KhuVuc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaBan
		{
			get
			{
				return this._MaBan;
			}
			set
			{
				if ((this._MaBan != value))
				{
					this.OnMaBanChanging(value);
					this.SendPropertyChanging();
					this._MaBan = value;
					this.SendPropertyChanged("MaBan");
					this.OnMaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenBan", DbType="NVarChar(50)")]
		public string TenBan
		{
			get
			{
				return this._TenBan;
			}
			set
			{
				if ((this._TenBan != value))
				{
					this.OnTenBanChanging(value);
					this.SendPropertyChanging();
					this._TenBan = value;
					this.SendPropertyChanged("TenBan");
					this.OnTenBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Int")]
		public System.Nullable<int> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhuVuc", DbType="NChar(50)")]
		public string MaKhuVuc
		{
			get
			{
				return this._MaKhuVuc;
			}
			set
			{
				if ((this._MaKhuVuc != value))
				{
					if (this._KhuVuc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhuVucChanging(value);
					this.SendPropertyChanging();
					this._MaKhuVuc = value;
					this.SendPropertyChanged("MaKhuVuc");
					this.OnMaKhuVucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ban_ChiTietHD", Storage="_ChiTietHDs", ThisKey="MaBan", OtherKey="MaBan")]
		public EntitySet<ChiTietHD> ChiTietHDs
		{
			get
			{
				return this._ChiTietHDs;
			}
			set
			{
				this._ChiTietHDs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ban_DanhSachMonGoi", Storage="_DanhSachMonGois", ThisKey="MaBan", OtherKey="MaBan")]
		public EntitySet<DanhSachMonGoi> DanhSachMonGois
		{
			get
			{
				return this._DanhSachMonGois;
			}
			set
			{
				this._DanhSachMonGois.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhuVuc_Ban", Storage="_KhuVuc", ThisKey="MaKhuVuc", OtherKey="MaKhuVuc", IsForeignKey=true)]
		public KhuVuc KhuVuc
		{
			get
			{
				return this._KhuVuc.Entity;
			}
			set
			{
				KhuVuc previousValue = this._KhuVuc.Entity;
				if (((previousValue != value) 
							|| (this._KhuVuc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhuVuc.Entity = null;
						previousValue.Bans.Remove(this);
					}
					this._KhuVuc.Entity = value;
					if ((value != null))
					{
						value.Bans.Add(this);
						this._MaKhuVuc = value.MaKhuVuc;
					}
					else
					{
						this._MaKhuVuc = default(string);
					}
					this.SendPropertyChanged("KhuVuc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietHDs(ChiTietHD entity)
		{
			this.SendPropertyChanging();
			entity.Ban = this;
		}
		
		private void detach_ChiTietHDs(ChiTietHD entity)
		{
			this.SendPropertyChanging();
			entity.Ban = null;
		}
		
		private void attach_DanhSachMonGois(DanhSachMonGoi entity)
		{
			this.SendPropertyChanging();
			entity.Ban = this;
		}
		
		private void detach_DanhSachMonGois(DanhSachMonGoi entity)
		{
			this.SendPropertyChanging();
			entity.Ban = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoanNhomNV")]
	public partial class TaiKhoanNhomNV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TaiKhoan;
		
		private string _MaNhomNV;
		
		private string _GhiChu;
		
		private EntityRef<NhomNhanVien> _NhomNhanVien;
		
		private EntityRef<TaiKhoan> _TaiKhoan1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnMaNhomNVChanging(string value);
    partial void OnMaNhomNVChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public TaiKhoanNhomNV()
		{
			this._NhomNhanVien = default(EntityRef<NhomNhanVien>);
			this._TaiKhoan1 = default(EntityRef<TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="NChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					if (this._TaiKhoan1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhomNV", DbType="NChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhomNV
		{
			get
			{
				return this._MaNhomNV;
			}
			set
			{
				if ((this._MaNhomNV != value))
				{
					if (this._NhomNhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhomNVChanging(value);
					this.SendPropertyChanging();
					this._MaNhomNV = value;
					this.SendPropertyChanged("MaNhomNV");
					this.OnMaNhomNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(50)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomNhanVien_TaiKhoanNhomNV", Storage="_NhomNhanVien", ThisKey="MaNhomNV", OtherKey="MaNhomNV", IsForeignKey=true)]
		public NhomNhanVien NhomNhanVien
		{
			get
			{
				return this._NhomNhanVien.Entity;
			}
			set
			{
				NhomNhanVien previousValue = this._NhomNhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhomNhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhomNhanVien.Entity = null;
						previousValue.TaiKhoanNhomNVs.Remove(this);
					}
					this._NhomNhanVien.Entity = value;
					if ((value != null))
					{
						value.TaiKhoanNhomNVs.Add(this);
						this._MaNhomNV = value.MaNhomNV;
					}
					else
					{
						this._MaNhomNV = default(string);
					}
					this.SendPropertyChanged("NhomNhanVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_TaiKhoanNhomNV", Storage="_TaiKhoan1", ThisKey="TaiKhoan", OtherKey="TenTaiKhoan", IsForeignKey=true)]
		public TaiKhoan TaiKhoan1
		{
			get
			{
				return this._TaiKhoan1.Entity;
			}
			set
			{
				TaiKhoan previousValue = this._TaiKhoan1.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoan1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoan1.Entity = null;
						previousValue.TaiKhoanNhomNVs.Remove(this);
					}
					this._TaiKhoan1.Entity = value;
					if ((value != null))
					{
						value.TaiKhoanNhomNVs.Add(this);
						this._TaiKhoan = value.TenTaiKhoan;
					}
					else
					{
						this._TaiKhoan = default(string);
					}
					this.SendPropertyChanged("TaiKhoan1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BangPhanCongCV")]
	public partial class BangPhanCongCV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CaLamViec;
		
		private System.DateTime _NgayLam;
		
		private string _MaNhanVien;
		
		private string _GhiChu;
		
		private EntityRef<CaLamViec> _CaLamViec1;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCaLamViecChanging(int value);
    partial void OnCaLamViecChanged();
    partial void OnNgayLamChanging(System.DateTime value);
    partial void OnNgayLamChanged();
    partial void OnMaNhanVienChanging(string value);
    partial void OnMaNhanVienChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public BangPhanCongCV()
		{
			this._CaLamViec1 = default(EntityRef<CaLamViec>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaLamViec", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CaLamViec
		{
			get
			{
				return this._CaLamViec;
			}
			set
			{
				if ((this._CaLamViec != value))
				{
					if (this._CaLamViec1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCaLamViecChanging(value);
					this.SendPropertyChanging();
					this._CaLamViec = value;
					this.SendPropertyChanged("CaLamViec");
					this.OnCaLamViecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLam", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime NgayLam
		{
			get
			{
				return this._NgayLam;
			}
			set
			{
				if ((this._NgayLam != value))
				{
					this.OnNgayLamChanging(value);
					this.SendPropertyChanging();
					this._NgayLam = value;
					this.SendPropertyChanged("NgayLam");
					this.OnNgayLamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="NChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(100)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CaLamViec_BangPhanCongCV", Storage="_CaLamViec1", ThisKey="CaLamViec", OtherKey="CaLamViec1", IsForeignKey=true)]
		public CaLamViec CaLamViec1
		{
			get
			{
				return this._CaLamViec1.Entity;
			}
			set
			{
				CaLamViec previousValue = this._CaLamViec1.Entity;
				if (((previousValue != value) 
							|| (this._CaLamViec1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CaLamViec1.Entity = null;
						previousValue.BangPhanCongCVs.Remove(this);
					}
					this._CaLamViec1.Entity = value;
					if ((value != null))
					{
						value.BangPhanCongCVs.Add(this);
						this._CaLamViec = value.CaLamViec1;
					}
					else
					{
						this._CaLamViec = default(int);
					}
					this.SendPropertyChanged("CaLamViec1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_BangPhanCongCV", Storage="_NhanVien", ThisKey="MaNhanVien", OtherKey="MaNhanVien", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.BangPhanCongCVs.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.BangPhanCongCVs.Add(this);
						this._MaNhanVien = value.MaNhanVien;
					}
					else
					{
						this._MaNhanVien = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CaLamViec")]
	public partial class CaLamViec : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CaLamViec1;
		
		private string _GioLamViec;
		
		private EntitySet<BangPhanCongCV> _BangPhanCongCVs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCaLamViec1Changing(int value);
    partial void OnCaLamViec1Changed();
    partial void OnGioLamViecChanging(string value);
    partial void OnGioLamViecChanged();
    #endregion
		
		public CaLamViec()
		{
			this._BangPhanCongCVs = new EntitySet<BangPhanCongCV>(new Action<BangPhanCongCV>(this.attach_BangPhanCongCVs), new Action<BangPhanCongCV>(this.detach_BangPhanCongCVs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CaLamViec", Storage="_CaLamViec1", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CaLamViec1
		{
			get
			{
				return this._CaLamViec1;
			}
			set
			{
				if ((this._CaLamViec1 != value))
				{
					this.OnCaLamViec1Changing(value);
					this.SendPropertyChanging();
					this._CaLamViec1 = value;
					this.SendPropertyChanged("CaLamViec1");
					this.OnCaLamViec1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioLamViec", DbType="NVarChar(50)")]
		public string GioLamViec
		{
			get
			{
				return this._GioLamViec;
			}
			set
			{
				if ((this._GioLamViec != value))
				{
					this.OnGioLamViecChanging(value);
					this.SendPropertyChanging();
					this._GioLamViec = value;
					this.SendPropertyChanged("GioLamViec");
					this.OnGioLamViecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CaLamViec_BangPhanCongCV", Storage="_BangPhanCongCVs", ThisKey="CaLamViec1", OtherKey="CaLamViec")]
		public EntitySet<BangPhanCongCV> BangPhanCongCVs
		{
			get
			{
				return this._BangPhanCongCVs;
			}
			set
			{
				this._BangPhanCongCVs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BangPhanCongCVs(BangPhanCongCV entity)
		{
			this.SendPropertyChanging();
			entity.CaLamViec1 = this;
		}
		
		private void detach_BangPhanCongCVs(BangPhanCongCV entity)
		{
			this.SendPropertyChanging();
			entity.CaLamViec1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietHD")]
	public partial class ChiTietHD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHoaDon;
		
		private int _MaBan;
		
		private string _MaMon;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<decimal> _DonGia;
		
		private EntityRef<Ban> _Ban;
		
		private EntityRef<HoaDon> _HoaDon;
		
		private EntityRef<Menu> _Menu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHoaDonChanging(int value);
    partial void OnMaHoaDonChanged();
    partial void OnMaBanChanging(int value);
    partial void OnMaBanChanged();
    partial void OnMaMonChanging(string value);
    partial void OnMaMonChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnDonGiaChanging(System.Nullable<decimal> value);
    partial void OnDonGiaChanged();
    #endregion
		
		public ChiTietHD()
		{
			this._Ban = default(EntityRef<Ban>);
			this._HoaDon = default(EntityRef<HoaDon>);
			this._Menu = default(EntityRef<Menu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoaDon", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaHoaDon
		{
			get
			{
				return this._MaHoaDon;
			}
			set
			{
				if ((this._MaHoaDon != value))
				{
					if (this._HoaDon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHoaDonChanging(value);
					this.SendPropertyChanging();
					this._MaHoaDon = value;
					this.SendPropertyChanged("MaHoaDon");
					this.OnMaHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBan", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaBan
		{
			get
			{
				return this._MaBan;
			}
			set
			{
				if ((this._MaBan != value))
				{
					if (this._Ban.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBanChanging(value);
					this.SendPropertyChanging();
					this._MaBan = value;
					this.SendPropertyChanged("MaBan");
					this.OnMaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMon", DbType="NChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaMon
		{
			get
			{
				return this._MaMon;
			}
			set
			{
				if ((this._MaMon != value))
				{
					if (this._Menu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaMonChanging(value);
					this.SendPropertyChanging();
					this._MaMon = value;
					this.SendPropertyChanged("MaMon");
					this.OnMaMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Money")]
		public System.Nullable<decimal> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ban_ChiTietHD", Storage="_Ban", ThisKey="MaBan", OtherKey="MaBan", IsForeignKey=true)]
		public Ban Ban
		{
			get
			{
				return this._Ban.Entity;
			}
			set
			{
				Ban previousValue = this._Ban.Entity;
				if (((previousValue != value) 
							|| (this._Ban.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ban.Entity = null;
						previousValue.ChiTietHDs.Remove(this);
					}
					this._Ban.Entity = value;
					if ((value != null))
					{
						value.ChiTietHDs.Add(this);
						this._MaBan = value.MaBan;
					}
					else
					{
						this._MaBan = default(int);
					}
					this.SendPropertyChanged("Ban");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon_ChiTietHD", Storage="_HoaDon", ThisKey="MaHoaDon", OtherKey="MaHoaDon", IsForeignKey=true)]
		public HoaDon HoaDon
		{
			get
			{
				return this._HoaDon.Entity;
			}
			set
			{
				HoaDon previousValue = this._HoaDon.Entity;
				if (((previousValue != value) 
							|| (this._HoaDon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoaDon.Entity = null;
						previousValue.ChiTietHDs.Remove(this);
					}
					this._HoaDon.Entity = value;
					if ((value != null))
					{
						value.ChiTietHDs.Add(this);
						this._MaHoaDon = value.MaHoaDon;
					}
					else
					{
						this._MaHoaDon = default(int);
					}
					this.SendPropertyChanged("HoaDon");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Menu_ChiTietHD", Storage="_Menu", ThisKey="MaMon", OtherKey="MaMon", IsForeignKey=true)]
		public Menu Menu
		{
			get
			{
				return this._Menu.Entity;
			}
			set
			{
				Menu previousValue = this._Menu.Entity;
				if (((previousValue != value) 
							|| (this._Menu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Menu.Entity = null;
						previousValue.ChiTietHDs.Remove(this);
					}
					this._Menu.Entity = value;
					if ((value != null))
					{
						value.ChiTietHDs.Add(this);
						this._MaMon = value.MaMon;
					}
					else
					{
						this._MaMon = default(string);
					}
					this.SendPropertyChanged("Menu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DanhSachMonGoi")]
	public partial class DanhSachMonGoi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaBan;
		
		private string _MaMon;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<decimal> _Gia;
		
		private EntityRef<Ban> _Ban;
		
		private EntityRef<Menu> _Menu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBanChanging(int value);
    partial void OnMaBanChanged();
    partial void OnMaMonChanging(string value);
    partial void OnMaMonChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnGiaChanging(System.Nullable<decimal> value);
    partial void OnGiaChanged();
    #endregion
		
		public DanhSachMonGoi()
		{
			this._Ban = default(EntityRef<Ban>);
			this._Menu = default(EntityRef<Menu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBan", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaBan
		{
			get
			{
				return this._MaBan;
			}
			set
			{
				if ((this._MaBan != value))
				{
					if (this._Ban.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBanChanging(value);
					this.SendPropertyChanging();
					this._MaBan = value;
					this.SendPropertyChanged("MaBan");
					this.OnMaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMon", DbType="NChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaMon
		{
			get
			{
				return this._MaMon;
			}
			set
			{
				if ((this._MaMon != value))
				{
					if (this._Menu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaMonChanging(value);
					this.SendPropertyChanging();
					this._MaMon = value;
					this.SendPropertyChanged("MaMon");
					this.OnMaMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Money")]
		public System.Nullable<decimal> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ban_DanhSachMonGoi", Storage="_Ban", ThisKey="MaBan", OtherKey="MaBan", IsForeignKey=true)]
		public Ban Ban
		{
			get
			{
				return this._Ban.Entity;
			}
			set
			{
				Ban previousValue = this._Ban.Entity;
				if (((previousValue != value) 
							|| (this._Ban.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ban.Entity = null;
						previousValue.DanhSachMonGois.Remove(this);
					}
					this._Ban.Entity = value;
					if ((value != null))
					{
						value.DanhSachMonGois.Add(this);
						this._MaBan = value.MaBan;
					}
					else
					{
						this._MaBan = default(int);
					}
					this.SendPropertyChanged("Ban");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Menu_DanhSachMonGoi", Storage="_Menu", ThisKey="MaMon", OtherKey="MaMon", IsForeignKey=true)]
		public Menu Menu
		{
			get
			{
				return this._Menu.Entity;
			}
			set
			{
				Menu previousValue = this._Menu.Entity;
				if (((previousValue != value) 
							|| (this._Menu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Menu.Entity = null;
						previousValue.DanhSachMonGois.Remove(this);
					}
					this._Menu.Entity = value;
					if ((value != null))
					{
						value.DanhSachMonGois.Add(this);
						this._MaMon = value.MaMon;
					}
					else
					{
						this._MaMon = default(string);
					}
					this.SendPropertyChanged("Menu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GiamGia")]
	public partial class GiamGia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaGiamGia;
		
		private string _TenSuKien;
		
		private System.Nullable<int> _PhantramGiam;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGiamGiaChanging(string value);
    partial void OnMaGiamGiaChanged();
    partial void OnTenSuKienChanging(string value);
    partial void OnTenSuKienChanged();
    partial void OnPhantramGiamChanging(System.Nullable<int> value);
    partial void OnPhantramGiamChanged();
    #endregion
		
		public GiamGia()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGiamGia", DbType="NChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaGiamGia
		{
			get
			{
				return this._MaGiamGia;
			}
			set
			{
				if ((this._MaGiamGia != value))
				{
					this.OnMaGiamGiaChanging(value);
					this.SendPropertyChanging();
					this._MaGiamGia = value;
					this.SendPropertyChanged("MaGiamGia");
					this.OnMaGiamGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSuKien", DbType="NChar(50)")]
		public string TenSuKien
		{
			get
			{
				return this._TenSuKien;
			}
			set
			{
				if ((this._TenSuKien != value))
				{
					this.OnTenSuKienChanging(value);
					this.SendPropertyChanging();
					this._TenSuKien = value;
					this.SendPropertyChanged("TenSuKien");
					this.OnTenSuKienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhantramGiam", DbType="Int")]
		public System.Nullable<int> PhantramGiam
		{
			get
			{
				return this._PhantramGiam;
			}
			set
			{
				if ((this._PhantramGiam != value))
				{
					this.OnPhantramGiamChanging(value);
					this.SendPropertyChanging();
					this._PhantramGiam = value;
					this.SendPropertyChanged("PhantramGiam");
					this.OnPhantramGiamChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDon")]
	public partial class HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHoaDon;
		
		private System.Nullable<System.DateTime> _NgayXuat;
		
		private System.Nullable<decimal> _TongTien;
		
		private string _MaGiamGia;
		
		private EntitySet<ChiTietHD> _ChiTietHDs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHoaDonChanging(int value);
    partial void OnMaHoaDonChanged();
    partial void OnNgayXuatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayXuatChanged();
    partial void OnTongTienChanging(System.Nullable<decimal> value);
    partial void OnTongTienChanged();
    partial void OnMaGiamGiaChanging(string value);
    partial void OnMaGiamGiaChanged();
    #endregion
		
		public HoaDon()
		{
			this._ChiTietHDs = new EntitySet<ChiTietHD>(new Action<ChiTietHD>(this.attach_ChiTietHDs), new Action<ChiTietHD>(this.detach_ChiTietHDs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoaDon", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaHoaDon
		{
			get
			{
				return this._MaHoaDon;
			}
			set
			{
				if ((this._MaHoaDon != value))
				{
					this.OnMaHoaDonChanging(value);
					this.SendPropertyChanging();
					this._MaHoaDon = value;
					this.SendPropertyChanged("MaHoaDon");
					this.OnMaHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayXuat", DbType="Date")]
		public System.Nullable<System.DateTime> NgayXuat
		{
			get
			{
				return this._NgayXuat;
			}
			set
			{
				if ((this._NgayXuat != value))
				{
					this.OnNgayXuatChanging(value);
					this.SendPropertyChanging();
					this._NgayXuat = value;
					this.SendPropertyChanged("NgayXuat");
					this.OnNgayXuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Money")]
		public System.Nullable<decimal> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGiamGia", DbType="NChar(50)")]
		public string MaGiamGia
		{
			get
			{
				return this._MaGiamGia;
			}
			set
			{
				if ((this._MaGiamGia != value))
				{
					this.OnMaGiamGiaChanging(value);
					this.SendPropertyChanging();
					this._MaGiamGia = value;
					this.SendPropertyChanged("MaGiamGia");
					this.OnMaGiamGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon_ChiTietHD", Storage="_ChiTietHDs", ThisKey="MaHoaDon", OtherKey="MaHoaDon")]
		public EntitySet<ChiTietHD> ChiTietHDs
		{
			get
			{
				return this._ChiTietHDs;
			}
			set
			{
				this._ChiTietHDs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietHDs(ChiTietHD entity)
		{
			this.SendPropertyChanging();
			entity.HoaDon = this;
		}
		
		private void detach_ChiTietHDs(ChiTietHD entity)
		{
			this.SendPropertyChanging();
			entity.HoaDon = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhoNguyenLieu")]
	public partial class KhoNguyenLieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNguyenLieu;
		
		private string _TenNguyenLieu;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<decimal> _DonGia;
		
		private string _DVT;
		
		private System.Nullable<System.DateTime> _NgayNhap;
		
		private EntitySet<NhomNguyenLieu> _NhomNguyenLieus;
		
		private EntitySet<QuanLyThuChi> _QuanLyThuChis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNguyenLieuChanging(string value);
    partial void OnMaNguyenLieuChanged();
    partial void OnTenNguyenLieuChanging(string value);
    partial void OnTenNguyenLieuChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnDonGiaChanging(System.Nullable<decimal> value);
    partial void OnDonGiaChanged();
    partial void OnDVTChanging(string value);
    partial void OnDVTChanged();
    partial void OnNgayNhapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayNhapChanged();
    #endregion
		
		public KhoNguyenLieu()
		{
			this._NhomNguyenLieus = new EntitySet<NhomNguyenLieu>(new Action<NhomNguyenLieu>(this.attach_NhomNguyenLieus), new Action<NhomNguyenLieu>(this.detach_NhomNguyenLieus));
			this._QuanLyThuChis = new EntitySet<QuanLyThuChi>(new Action<QuanLyThuChi>(this.attach_QuanLyThuChis), new Action<QuanLyThuChi>(this.detach_QuanLyThuChis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguyenLieu", DbType="NChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNguyenLieu
		{
			get
			{
				return this._MaNguyenLieu;
			}
			set
			{
				if ((this._MaNguyenLieu != value))
				{
					this.OnMaNguyenLieuChanging(value);
					this.SendPropertyChanging();
					this._MaNguyenLieu = value;
					this.SendPropertyChanged("MaNguyenLieu");
					this.OnMaNguyenLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNguyenLieu", DbType="NChar(50)")]
		public string TenNguyenLieu
		{
			get
			{
				return this._TenNguyenLieu;
			}
			set
			{
				if ((this._TenNguyenLieu != value))
				{
					this.OnTenNguyenLieuChanging(value);
					this.SendPropertyChanging();
					this._TenNguyenLieu = value;
					this.SendPropertyChanged("TenNguyenLieu");
					this.OnTenNguyenLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Money")]
		public System.Nullable<decimal> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVT", DbType="NChar(10)")]
		public string DVT
		{
			get
			{
				return this._DVT;
			}
			set
			{
				if ((this._DVT != value))
				{
					this.OnDVTChanging(value);
					this.SendPropertyChanging();
					this._DVT = value;
					this.SendPropertyChanged("DVT");
					this.OnDVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNhap", DbType="Date")]
		public System.Nullable<System.DateTime> NgayNhap
		{
			get
			{
				return this._NgayNhap;
			}
			set
			{
				if ((this._NgayNhap != value))
				{
					this.OnNgayNhapChanging(value);
					this.SendPropertyChanging();
					this._NgayNhap = value;
					this.SendPropertyChanged("NgayNhap");
					this.OnNgayNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhoNguyenLieu_NhomNguyenLieu", Storage="_NhomNguyenLieus", ThisKey="MaNguyenLieu", OtherKey="MaNguyenLieu")]
		public EntitySet<NhomNguyenLieu> NhomNguyenLieus
		{
			get
			{
				return this._NhomNguyenLieus;
			}
			set
			{
				this._NhomNguyenLieus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhoNguyenLieu_QuanLyThuChi", Storage="_QuanLyThuChis", ThisKey="MaNguyenLieu", OtherKey="MaNguyenLieu")]
		public EntitySet<QuanLyThuChi> QuanLyThuChis
		{
			get
			{
				return this._QuanLyThuChis;
			}
			set
			{
				this._QuanLyThuChis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NhomNguyenLieus(NhomNguyenLieu entity)
		{
			this.SendPropertyChanging();
			entity.KhoNguyenLieu = this;
		}
		
		private void detach_NhomNguyenLieus(NhomNguyenLieu entity)
		{
			this.SendPropertyChanging();
			entity.KhoNguyenLieu = null;
		}
		
		private void attach_QuanLyThuChis(QuanLyThuChi entity)
		{
			this.SendPropertyChanging();
			entity.KhoNguyenLieu = this;
		}
		
		private void detach_QuanLyThuChis(QuanLyThuChi entity)
		{
			this.SendPropertyChanging();
			entity.KhoNguyenLieu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhuVuc")]
	public partial class KhuVuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKhuVuc;
		
		private System.Nullable<int> _SoLuongBan;
		
		private string _TenKhuVuc;
		
		private EntitySet<Ban> _Bans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhuVucChanging(string value);
    partial void OnMaKhuVucChanged();
    partial void OnSoLuongBanChanging(System.Nullable<int> value);
    partial void OnSoLuongBanChanged();
    partial void OnTenKhuVucChanging(string value);
    partial void OnTenKhuVucChanged();
    #endregion
		
		public KhuVuc()
		{
			this._Bans = new EntitySet<Ban>(new Action<Ban>(this.attach_Bans), new Action<Ban>(this.detach_Bans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhuVuc", DbType="NChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKhuVuc
		{
			get
			{
				return this._MaKhuVuc;
			}
			set
			{
				if ((this._MaKhuVuc != value))
				{
					this.OnMaKhuVucChanging(value);
					this.SendPropertyChanging();
					this._MaKhuVuc = value;
					this.SendPropertyChanged("MaKhuVuc");
					this.OnMaKhuVucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongBan", DbType="Int")]
		public System.Nullable<int> SoLuongBan
		{
			get
			{
				return this._SoLuongBan;
			}
			set
			{
				if ((this._SoLuongBan != value))
				{
					this.OnSoLuongBanChanging(value);
					this.SendPropertyChanging();
					this._SoLuongBan = value;
					this.SendPropertyChanged("SoLuongBan");
					this.OnSoLuongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhuVuc", DbType="NVarChar(50)")]
		public string TenKhuVuc
		{
			get
			{
				return this._TenKhuVuc;
			}
			set
			{
				if ((this._TenKhuVuc != value))
				{
					this.OnTenKhuVucChanging(value);
					this.SendPropertyChanging();
					this._TenKhuVuc = value;
					this.SendPropertyChanged("TenKhuVuc");
					this.OnTenKhuVucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhuVuc_Ban", Storage="_Bans", ThisKey="MaKhuVuc", OtherKey="MaKhuVuc")]
		public EntitySet<Ban> Bans
		{
			get
			{
				return this._Bans;
			}
			set
			{
				this._Bans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Bans(Ban entity)
		{
			this.SendPropertyChanging();
			entity.KhuVuc = this;
		}
		
		private void detach_Bans(Ban entity)
		{
			this.SendPropertyChanging();
			entity.KhuVuc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ManHinh")]
	public partial class ManHinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaManHinh;
		
		private string _TenManHinh;
		
		private EntitySet<PhanQuyen> _PhanQuyens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaManHinhChanging(string value);
    partial void OnMaManHinhChanged();
    partial void OnTenManHinhChanging(string value);
    partial void OnTenManHinhChanged();
    #endregion
		
		public ManHinh()
		{
			this._PhanQuyens = new EntitySet<PhanQuyen>(new Action<PhanQuyen>(this.attach_PhanQuyens), new Action<PhanQuyen>(this.detach_PhanQuyens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaManHinh", DbType="NChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaManHinh
		{
			get
			{
				return this._MaManHinh;
			}
			set
			{
				if ((this._MaManHinh != value))
				{
					this.OnMaManHinhChanging(value);
					this.SendPropertyChanging();
					this._MaManHinh = value;
					this.SendPropertyChanged("MaManHinh");
					this.OnMaManHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenManHinh", DbType="NVarChar(50)")]
		public string TenManHinh
		{
			get
			{
				return this._TenManHinh;
			}
			set
			{
				if ((this._TenManHinh != value))
				{
					this.OnTenManHinhChanging(value);
					this.SendPropertyChanging();
					this._TenManHinh = value;
					this.SendPropertyChanged("TenManHinh");
					this.OnTenManHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ManHinh_PhanQuyen", Storage="_PhanQuyens", ThisKey="MaManHinh", OtherKey="MaManHinh")]
		public EntitySet<PhanQuyen> PhanQuyens
		{
			get
			{
				return this._PhanQuyens;
			}
			set
			{
				this._PhanQuyens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhanQuyens(PhanQuyen entity)
		{
			this.SendPropertyChanging();
			entity.ManHinh = this;
		}
		
		private void detach_PhanQuyens(PhanQuyen entity)
		{
			this.SendPropertyChanging();
			entity.ManHinh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Menu")]
	public partial class Menu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaMon;
		
		private string _TenMon;
		
		private System.Nullable<decimal> _Gia;
		
		private string _DVT;
		
		private System.Data.Linq.Binary _HinhAnh;
		
		private EntitySet<ChiTietHD> _ChiTietHDs;
		
		private EntitySet<DanhSachMonGoi> _DanhSachMonGois;
		
		private EntitySet<NhomNguyenLieu> _NhomNguyenLieus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMonChanging(string value);
    partial void OnMaMonChanged();
    partial void OnTenMonChanging(string value);
    partial void OnTenMonChanged();
    partial void OnGiaChanging(System.Nullable<decimal> value);
    partial void OnGiaChanged();
    partial void OnDVTChanging(string value);
    partial void OnDVTChanged();
    partial void OnHinhAnhChanging(System.Data.Linq.Binary value);
    partial void OnHinhAnhChanged();
    #endregion
		
		public Menu()
		{
			this._ChiTietHDs = new EntitySet<ChiTietHD>(new Action<ChiTietHD>(this.attach_ChiTietHDs), new Action<ChiTietHD>(this.detach_ChiTietHDs));
			this._DanhSachMonGois = new EntitySet<DanhSachMonGoi>(new Action<DanhSachMonGoi>(this.attach_DanhSachMonGois), new Action<DanhSachMonGoi>(this.detach_DanhSachMonGois));
			this._NhomNguyenLieus = new EntitySet<NhomNguyenLieu>(new Action<NhomNguyenLieu>(this.attach_NhomNguyenLieus), new Action<NhomNguyenLieu>(this.detach_NhomNguyenLieus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMon", DbType="NChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaMon
		{
			get
			{
				return this._MaMon;
			}
			set
			{
				if ((this._MaMon != value))
				{
					this.OnMaMonChanging(value);
					this.SendPropertyChanging();
					this._MaMon = value;
					this.SendPropertyChanged("MaMon");
					this.OnMaMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMon", DbType="NChar(50)")]
		public string TenMon
		{
			get
			{
				return this._TenMon;
			}
			set
			{
				if ((this._TenMon != value))
				{
					this.OnTenMonChanging(value);
					this.SendPropertyChanging();
					this._TenMon = value;
					this.SendPropertyChanged("TenMon");
					this.OnTenMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Money")]
		public System.Nullable<decimal> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVT", DbType="NChar(10)")]
		public string DVT
		{
			get
			{
				return this._DVT;
			}
			set
			{
				if ((this._DVT != value))
				{
					this.OnDVTChanging(value);
					this.SendPropertyChanging();
					this._DVT = value;
					this.SendPropertyChanged("DVT");
					this.OnDVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Menu_ChiTietHD", Storage="_ChiTietHDs", ThisKey="MaMon", OtherKey="MaMon")]
		public EntitySet<ChiTietHD> ChiTietHDs
		{
			get
			{
				return this._ChiTietHDs;
			}
			set
			{
				this._ChiTietHDs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Menu_DanhSachMonGoi", Storage="_DanhSachMonGois", ThisKey="MaMon", OtherKey="MaMon")]
		public EntitySet<DanhSachMonGoi> DanhSachMonGois
		{
			get
			{
				return this._DanhSachMonGois;
			}
			set
			{
				this._DanhSachMonGois.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Menu_NhomNguyenLieu", Storage="_NhomNguyenLieus", ThisKey="MaMon", OtherKey="MaMon")]
		public EntitySet<NhomNguyenLieu> NhomNguyenLieus
		{
			get
			{
				return this._NhomNguyenLieus;
			}
			set
			{
				this._NhomNguyenLieus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietHDs(ChiTietHD entity)
		{
			this.SendPropertyChanging();
			entity.Menu = this;
		}
		
		private void detach_ChiTietHDs(ChiTietHD entity)
		{
			this.SendPropertyChanging();
			entity.Menu = null;
		}
		
		private void attach_DanhSachMonGois(DanhSachMonGoi entity)
		{
			this.SendPropertyChanging();
			entity.Menu = this;
		}
		
		private void detach_DanhSachMonGois(DanhSachMonGoi entity)
		{
			this.SendPropertyChanging();
			entity.Menu = null;
		}
		
		private void attach_NhomNguyenLieus(NhomNguyenLieu entity)
		{
			this.SendPropertyChanging();
			entity.Menu = this;
		}
		
		private void detach_NhomNguyenLieus(NhomNguyenLieu entity)
		{
			this.SendPropertyChanging();
			entity.Menu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhanVien;
		
		private string _TenNhanVien;
		
		private string _MaNhomNV;
		
		private EntitySet<BangPhanCongCV> _BangPhanCongCVs;
		
		private EntityRef<NhomNhanVien> _NhomNhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhanVienChanging(string value);
    partial void OnMaNhanVienChanged();
    partial void OnTenNhanVienChanging(string value);
    partial void OnTenNhanVienChanged();
    partial void OnMaNhomNVChanging(string value);
    partial void OnMaNhomNVChanged();
    #endregion
		
		public NhanVien()
		{
			this._BangPhanCongCVs = new EntitySet<BangPhanCongCV>(new Action<BangPhanCongCV>(this.attach_BangPhanCongCVs), new Action<BangPhanCongCV>(this.detach_BangPhanCongCVs));
			this._NhomNhanVien = default(EntityRef<NhomNhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="NChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhanVien", DbType="NChar(50)")]
		public string TenNhanVien
		{
			get
			{
				return this._TenNhanVien;
			}
			set
			{
				if ((this._TenNhanVien != value))
				{
					this.OnTenNhanVienChanging(value);
					this.SendPropertyChanging();
					this._TenNhanVien = value;
					this.SendPropertyChanged("TenNhanVien");
					this.OnTenNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhomNV", DbType="NChar(50)")]
		public string MaNhomNV
		{
			get
			{
				return this._MaNhomNV;
			}
			set
			{
				if ((this._MaNhomNV != value))
				{
					if (this._NhomNhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhomNVChanging(value);
					this.SendPropertyChanging();
					this._MaNhomNV = value;
					this.SendPropertyChanged("MaNhomNV");
					this.OnMaNhomNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_BangPhanCongCV", Storage="_BangPhanCongCVs", ThisKey="MaNhanVien", OtherKey="MaNhanVien")]
		public EntitySet<BangPhanCongCV> BangPhanCongCVs
		{
			get
			{
				return this._BangPhanCongCVs;
			}
			set
			{
				this._BangPhanCongCVs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomNhanVien_NhanVien", Storage="_NhomNhanVien", ThisKey="MaNhomNV", OtherKey="MaNhomNV", IsForeignKey=true)]
		public NhomNhanVien NhomNhanVien
		{
			get
			{
				return this._NhomNhanVien.Entity;
			}
			set
			{
				NhomNhanVien previousValue = this._NhomNhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhomNhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhomNhanVien.Entity = null;
						previousValue.NhanViens.Remove(this);
					}
					this._NhomNhanVien.Entity = value;
					if ((value != null))
					{
						value.NhanViens.Add(this);
						this._MaNhomNV = value.MaNhomNV;
					}
					else
					{
						this._MaNhomNV = default(string);
					}
					this.SendPropertyChanged("NhomNhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BangPhanCongCVs(BangPhanCongCV entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_BangPhanCongCVs(BangPhanCongCV entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhomNguyenLieu")]
	public partial class NhomNguyenLieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaMon;
		
		private string _MaNguyenLieu;
		
		private System.Nullable<int> _SoLuongSuDung;
		
		private EntityRef<KhoNguyenLieu> _KhoNguyenLieu;
		
		private EntityRef<Menu> _Menu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMonChanging(string value);
    partial void OnMaMonChanged();
    partial void OnMaNguyenLieuChanging(string value);
    partial void OnMaNguyenLieuChanged();
    partial void OnSoLuongSuDungChanging(System.Nullable<int> value);
    partial void OnSoLuongSuDungChanged();
    #endregion
		
		public NhomNguyenLieu()
		{
			this._KhoNguyenLieu = default(EntityRef<KhoNguyenLieu>);
			this._Menu = default(EntityRef<Menu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMon", DbType="NChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaMon
		{
			get
			{
				return this._MaMon;
			}
			set
			{
				if ((this._MaMon != value))
				{
					if (this._Menu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaMonChanging(value);
					this.SendPropertyChanging();
					this._MaMon = value;
					this.SendPropertyChanged("MaMon");
					this.OnMaMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguyenLieu", DbType="NChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNguyenLieu
		{
			get
			{
				return this._MaNguyenLieu;
			}
			set
			{
				if ((this._MaNguyenLieu != value))
				{
					if (this._KhoNguyenLieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNguyenLieuChanging(value);
					this.SendPropertyChanging();
					this._MaNguyenLieu = value;
					this.SendPropertyChanged("MaNguyenLieu");
					this.OnMaNguyenLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongSuDung", DbType="Int")]
		public System.Nullable<int> SoLuongSuDung
		{
			get
			{
				return this._SoLuongSuDung;
			}
			set
			{
				if ((this._SoLuongSuDung != value))
				{
					this.OnSoLuongSuDungChanging(value);
					this.SendPropertyChanging();
					this._SoLuongSuDung = value;
					this.SendPropertyChanged("SoLuongSuDung");
					this.OnSoLuongSuDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhoNguyenLieu_NhomNguyenLieu", Storage="_KhoNguyenLieu", ThisKey="MaNguyenLieu", OtherKey="MaNguyenLieu", IsForeignKey=true)]
		public KhoNguyenLieu KhoNguyenLieu
		{
			get
			{
				return this._KhoNguyenLieu.Entity;
			}
			set
			{
				KhoNguyenLieu previousValue = this._KhoNguyenLieu.Entity;
				if (((previousValue != value) 
							|| (this._KhoNguyenLieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhoNguyenLieu.Entity = null;
						previousValue.NhomNguyenLieus.Remove(this);
					}
					this._KhoNguyenLieu.Entity = value;
					if ((value != null))
					{
						value.NhomNguyenLieus.Add(this);
						this._MaNguyenLieu = value.MaNguyenLieu;
					}
					else
					{
						this._MaNguyenLieu = default(string);
					}
					this.SendPropertyChanged("KhoNguyenLieu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Menu_NhomNguyenLieu", Storage="_Menu", ThisKey="MaMon", OtherKey="MaMon", IsForeignKey=true)]
		public Menu Menu
		{
			get
			{
				return this._Menu.Entity;
			}
			set
			{
				Menu previousValue = this._Menu.Entity;
				if (((previousValue != value) 
							|| (this._Menu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Menu.Entity = null;
						previousValue.NhomNguyenLieus.Remove(this);
					}
					this._Menu.Entity = value;
					if ((value != null))
					{
						value.NhomNguyenLieus.Add(this);
						this._MaMon = value.MaMon;
					}
					else
					{
						this._MaMon = default(string);
					}
					this.SendPropertyChanged("Menu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhomNhanVien")]
	public partial class NhomNhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhomNV;
		
		private string _TenNhomNV;
		
		private EntitySet<TaiKhoanNhomNV> _TaiKhoanNhomNVs;
		
		private EntitySet<NhanVien> _NhanViens;
		
		private EntitySet<PhanQuyen> _PhanQuyens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhomNVChanging(string value);
    partial void OnMaNhomNVChanged();
    partial void OnTenNhomNVChanging(string value);
    partial void OnTenNhomNVChanged();
    #endregion
		
		public NhomNhanVien()
		{
			this._TaiKhoanNhomNVs = new EntitySet<TaiKhoanNhomNV>(new Action<TaiKhoanNhomNV>(this.attach_TaiKhoanNhomNVs), new Action<TaiKhoanNhomNV>(this.detach_TaiKhoanNhomNVs));
			this._NhanViens = new EntitySet<NhanVien>(new Action<NhanVien>(this.attach_NhanViens), new Action<NhanVien>(this.detach_NhanViens));
			this._PhanQuyens = new EntitySet<PhanQuyen>(new Action<PhanQuyen>(this.attach_PhanQuyens), new Action<PhanQuyen>(this.detach_PhanQuyens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhomNV", DbType="NChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhomNV
		{
			get
			{
				return this._MaNhomNV;
			}
			set
			{
				if ((this._MaNhomNV != value))
				{
					this.OnMaNhomNVChanging(value);
					this.SendPropertyChanging();
					this._MaNhomNV = value;
					this.SendPropertyChanged("MaNhomNV");
					this.OnMaNhomNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhomNV", DbType="NVarChar(50)")]
		public string TenNhomNV
		{
			get
			{
				return this._TenNhomNV;
			}
			set
			{
				if ((this._TenNhomNV != value))
				{
					this.OnTenNhomNVChanging(value);
					this.SendPropertyChanging();
					this._TenNhomNV = value;
					this.SendPropertyChanged("TenNhomNV");
					this.OnTenNhomNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomNhanVien_TaiKhoanNhomNV", Storage="_TaiKhoanNhomNVs", ThisKey="MaNhomNV", OtherKey="MaNhomNV")]
		public EntitySet<TaiKhoanNhomNV> TaiKhoanNhomNVs
		{
			get
			{
				return this._TaiKhoanNhomNVs;
			}
			set
			{
				this._TaiKhoanNhomNVs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomNhanVien_NhanVien", Storage="_NhanViens", ThisKey="MaNhomNV", OtherKey="MaNhomNV")]
		public EntitySet<NhanVien> NhanViens
		{
			get
			{
				return this._NhanViens;
			}
			set
			{
				this._NhanViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomNhanVien_PhanQuyen", Storage="_PhanQuyens", ThisKey="MaNhomNV", OtherKey="MaNhomNV")]
		public EntitySet<PhanQuyen> PhanQuyens
		{
			get
			{
				return this._PhanQuyens;
			}
			set
			{
				this._PhanQuyens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TaiKhoanNhomNVs(TaiKhoanNhomNV entity)
		{
			this.SendPropertyChanging();
			entity.NhomNhanVien = this;
		}
		
		private void detach_TaiKhoanNhomNVs(TaiKhoanNhomNV entity)
		{
			this.SendPropertyChanging();
			entity.NhomNhanVien = null;
		}
		
		private void attach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.NhomNhanVien = this;
		}
		
		private void detach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.NhomNhanVien = null;
		}
		
		private void attach_PhanQuyens(PhanQuyen entity)
		{
			this.SendPropertyChanging();
			entity.NhomNhanVien = this;
		}
		
		private void detach_PhanQuyens(PhanQuyen entity)
		{
			this.SendPropertyChanging();
			entity.NhomNhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhanQuyen")]
	public partial class PhanQuyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhomNV;
		
		private string _MaManHinh;
		
		private System.Nullable<bool> _CoQuyen;
		
		private EntityRef<ManHinh> _ManHinh;
		
		private EntityRef<NhomNhanVien> _NhomNhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhomNVChanging(string value);
    partial void OnMaNhomNVChanged();
    partial void OnMaManHinhChanging(string value);
    partial void OnMaManHinhChanged();
    partial void OnCoQuyenChanging(System.Nullable<bool> value);
    partial void OnCoQuyenChanged();
    #endregion
		
		public PhanQuyen()
		{
			this._ManHinh = default(EntityRef<ManHinh>);
			this._NhomNhanVien = default(EntityRef<NhomNhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhomNV", DbType="NChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhomNV
		{
			get
			{
				return this._MaNhomNV;
			}
			set
			{
				if ((this._MaNhomNV != value))
				{
					if (this._NhomNhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhomNVChanging(value);
					this.SendPropertyChanging();
					this._MaNhomNV = value;
					this.SendPropertyChanged("MaNhomNV");
					this.OnMaNhomNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaManHinh", DbType="NChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaManHinh
		{
			get
			{
				return this._MaManHinh;
			}
			set
			{
				if ((this._MaManHinh != value))
				{
					if (this._ManHinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaManHinhChanging(value);
					this.SendPropertyChanging();
					this._MaManHinh = value;
					this.SendPropertyChanged("MaManHinh");
					this.OnMaManHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoQuyen", DbType="Bit")]
		public System.Nullable<bool> CoQuyen
		{
			get
			{
				return this._CoQuyen;
			}
			set
			{
				if ((this._CoQuyen != value))
				{
					this.OnCoQuyenChanging(value);
					this.SendPropertyChanging();
					this._CoQuyen = value;
					this.SendPropertyChanged("CoQuyen");
					this.OnCoQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ManHinh_PhanQuyen", Storage="_ManHinh", ThisKey="MaManHinh", OtherKey="MaManHinh", IsForeignKey=true)]
		public ManHinh ManHinh
		{
			get
			{
				return this._ManHinh.Entity;
			}
			set
			{
				ManHinh previousValue = this._ManHinh.Entity;
				if (((previousValue != value) 
							|| (this._ManHinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ManHinh.Entity = null;
						previousValue.PhanQuyens.Remove(this);
					}
					this._ManHinh.Entity = value;
					if ((value != null))
					{
						value.PhanQuyens.Add(this);
						this._MaManHinh = value.MaManHinh;
					}
					else
					{
						this._MaManHinh = default(string);
					}
					this.SendPropertyChanged("ManHinh");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomNhanVien_PhanQuyen", Storage="_NhomNhanVien", ThisKey="MaNhomNV", OtherKey="MaNhomNV", IsForeignKey=true)]
		public NhomNhanVien NhomNhanVien
		{
			get
			{
				return this._NhomNhanVien.Entity;
			}
			set
			{
				NhomNhanVien previousValue = this._NhomNhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhomNhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhomNhanVien.Entity = null;
						previousValue.PhanQuyens.Remove(this);
					}
					this._NhomNhanVien.Entity = value;
					if ((value != null))
					{
						value.PhanQuyens.Add(this);
						this._MaNhomNV = value.MaNhomNV;
					}
					else
					{
						this._MaNhomNV = default(string);
					}
					this.SendPropertyChanged("NhomNhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QuanLyThuChi")]
	public partial class QuanLyThuChi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHoaDon;
		
		private string _MaNguyenLieu;
		
		private System.Nullable<System.DateTime> _NgayThongKe;
		
		private System.Nullable<decimal> _TongSo;
		
		private EntityRef<KhoNguyenLieu> _KhoNguyenLieu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHoaDonChanging(string value);
    partial void OnMaHoaDonChanged();
    partial void OnMaNguyenLieuChanging(string value);
    partial void OnMaNguyenLieuChanged();
    partial void OnNgayThongKeChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayThongKeChanged();
    partial void OnTongSoChanging(System.Nullable<decimal> value);
    partial void OnTongSoChanged();
    #endregion
		
		public QuanLyThuChi()
		{
			this._KhoNguyenLieu = default(EntityRef<KhoNguyenLieu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoaDon", DbType="NChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHoaDon
		{
			get
			{
				return this._MaHoaDon;
			}
			set
			{
				if ((this._MaHoaDon != value))
				{
					this.OnMaHoaDonChanging(value);
					this.SendPropertyChanging();
					this._MaHoaDon = value;
					this.SendPropertyChanged("MaHoaDon");
					this.OnMaHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguyenLieu", DbType="NChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNguyenLieu
		{
			get
			{
				return this._MaNguyenLieu;
			}
			set
			{
				if ((this._MaNguyenLieu != value))
				{
					if (this._KhoNguyenLieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNguyenLieuChanging(value);
					this.SendPropertyChanging();
					this._MaNguyenLieu = value;
					this.SendPropertyChanged("MaNguyenLieu");
					this.OnMaNguyenLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThongKe", DbType="Date")]
		public System.Nullable<System.DateTime> NgayThongKe
		{
			get
			{
				return this._NgayThongKe;
			}
			set
			{
				if ((this._NgayThongKe != value))
				{
					this.OnNgayThongKeChanging(value);
					this.SendPropertyChanging();
					this._NgayThongKe = value;
					this.SendPropertyChanged("NgayThongKe");
					this.OnNgayThongKeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongSo", DbType="Money")]
		public System.Nullable<decimal> TongSo
		{
			get
			{
				return this._TongSo;
			}
			set
			{
				if ((this._TongSo != value))
				{
					this.OnTongSoChanging(value);
					this.SendPropertyChanging();
					this._TongSo = value;
					this.SendPropertyChanged("TongSo");
					this.OnTongSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhoNguyenLieu_QuanLyThuChi", Storage="_KhoNguyenLieu", ThisKey="MaNguyenLieu", OtherKey="MaNguyenLieu", IsForeignKey=true)]
		public KhoNguyenLieu KhoNguyenLieu
		{
			get
			{
				return this._KhoNguyenLieu.Entity;
			}
			set
			{
				KhoNguyenLieu previousValue = this._KhoNguyenLieu.Entity;
				if (((previousValue != value) 
							|| (this._KhoNguyenLieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhoNguyenLieu.Entity = null;
						previousValue.QuanLyThuChis.Remove(this);
					}
					this._KhoNguyenLieu.Entity = value;
					if ((value != null))
					{
						value.QuanLyThuChis.Add(this);
						this._MaNguyenLieu = value.MaNguyenLieu;
					}
					else
					{
						this._MaNguyenLieu = default(string);
					}
					this.SendPropertyChanged("KhoNguyenLieu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenTaiKhoan;
		
		private string _MatKhau;
		
		private EntitySet<TaiKhoanNhomNV> _TaiKhoanNhomNVs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenTaiKhoanChanging(string value);
    partial void OnTenTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    #endregion
		
		public TaiKhoan()
		{
			this._TaiKhoanNhomNVs = new EntitySet<TaiKhoanNhomNV>(new Action<TaiKhoanNhomNV>(this.attach_TaiKhoanNhomNVs), new Action<TaiKhoanNhomNV>(this.detach_TaiKhoanNhomNVs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTaiKhoan", DbType="NChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenTaiKhoan
		{
			get
			{
				return this._TenTaiKhoan;
			}
			set
			{
				if ((this._TenTaiKhoan != value))
				{
					this.OnTenTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TenTaiKhoan = value;
					this.SendPropertyChanged("TenTaiKhoan");
					this.OnTenTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NChar(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_TaiKhoanNhomNV", Storage="_TaiKhoanNhomNVs", ThisKey="TenTaiKhoan", OtherKey="TaiKhoan")]
		public EntitySet<TaiKhoanNhomNV> TaiKhoanNhomNVs
		{
			get
			{
				return this._TaiKhoanNhomNVs;
			}
			set
			{
				this._TaiKhoanNhomNVs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TaiKhoanNhomNVs(TaiKhoanNhomNV entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan1 = this;
		}
		
		private void detach_TaiKhoanNhomNVs(TaiKhoanNhomNV entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan1 = null;
		}
	}
}
#pragma warning restore 1591
